apiVersion: v1
data:
  FRONTEND_URL: {{ .Values.ingressurlfe }}
  POSTGRES_DB: bunny_books
  POSTGRES_HOST: db
  POSTGRES_PASSWORD: need-to-replace
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-backend
---
apiVersion: v1
data:
  POSTGRES_DB: bunny_books
  POSTGRES_PASSWORD: need-to-replace
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-db